hsv_h: 0.7
hsv_s: 0.7
hsv_v: 0.9
degrees: 45
translate: 0.1
scale: 1.0
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 0.5
mixup: 0.0
copy_paste: 0.0
copy_paste_mode: flip
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
lr0: 0.002
lrf: 0.01